// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8rXvlMDfR-x00MLW6UMWYuB9E-HhFrvg',
    appId: '1:495272238968:web:b96d2f35420f6dd97d728d',
    messagingSenderId: '495272238968',
    projectId: 'mycommerce-9225f',
    authDomain: 'mycommerce-9225f.firebaseapp.com',
    storageBucket: 'mycommerce-9225f.appspot.com',
    measurementId: 'G-PPCPR6T9LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnGtvZKECiQkWjV8CHLYHXzFkihTjhKE',
    appId: '1:495272238968:android:5b397edb8c7ff7107d728d',
    messagingSenderId: '495272238968',
    projectId: 'mycommerce-9225f',
    storageBucket: 'mycommerce-9225f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJjtvpfoXAb9Jpb_IW4jPOxM5Fchl4Xc',
    appId: '1:495272238968:ios:0dd042740bacbcf47d728d',
    messagingSenderId: '495272238968',
    projectId: 'mycommerce-9225f',
    storageBucket: 'mycommerce-9225f.appspot.com',
    iosClientId:
        '495272238968-i9b6t05gprqi1c6fb3binl2jkepsc0ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.myCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcJjtvpfoXAb9Jpb_IW4jPOxM5Fchl4Xc',
    appId: '1:495272238968:ios:b5399850a571352a7d728d',
    messagingSenderId: '495272238968',
    projectId: 'mycommerce-9225f',
    storageBucket: 'mycommerce-9225f.appspot.com',
    iosClientId:
        '495272238968-kj02krdjpmsvbr0to0s8pi1uufhiqcfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myCommerce.RunnerTests',
  );
}
